// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkB7_pT_TT5Y2gSXIus8Osw5WiIdY57N4',
    appId: '1:520718220147:web:22383a143d74645d8f6306',
    messagingSenderId: '520718220147',
    projectId: 'qo-lber',
    authDomain: 'qo-lber.firebaseapp.com',
    storageBucket: 'qo-lber.firebasestorage.app',
    measurementId: 'G-6S12HJL2WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXuUxcFATUCJtsJUnfe_8I5F_yG4ht5g',
    appId: '1:520718220147:android:e56b0a153d497fcf8f6306',
    messagingSenderId: '520718220147',
    projectId: 'qo-lber',
    storageBucket: 'qo-lber.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkB7_pT_TT5Y2gSXIus8Osw5WiIdY57N4',
    appId: '1:520718220147:web:a11cd1abcd8694678f6306',
    messagingSenderId: '520718220147',
    projectId: 'qo-lber',
    authDomain: 'qo-lber.firebaseapp.com',
    storageBucket: 'qo-lber.firebasestorage.app',
    measurementId: 'G-E1NM3ZS92X',
  );
}
